### ISSUE TITLE
为什么用dawa登录之后，就白屏很久，而且点击反应特别慢了，甚至点击的时候直接闪退出来了

### ISSUE THREAD

**Issue by zzq5636243** [GitLqr/LQRWeChat#11]
点击切换首页的时候，反应就特别慢，卡在那了，是手机的原因吗？
点击通讯录就会直接报错卡死了
MessageFragment的175行还报错了，addInArray been called, this = com.lqr.ninegridimageview.LQRNineGridImageView{44ecb8e8 V.E..... ......ID 0,15-104,113 #7f0e0180 app:id/ngiv}call stack =
                                                           java.lang.Throwable: addInArray
还有：这个是进入的时候会一直包
1/execute Transaction: [id: 2201,  method: FriendService/getFriends] exception
                                                               java.lang.StackOverflowError
at $Proxy10.getFriends(Native Method)
                                                                   at com.lqr.wechat.nimsdk.NimFriendSDK.getFriends(NimFriendSDK.java:59)
                                                                   at com.lqr.wechat.fragment.ContactsFragment.initData(ContactsFragment.java:92)
这是报错的地方

**Comment by GitLqr** [comment]
之前偶尔有遇到过，但是一直找不到原因，待之后有空解决

**Comment by zzq5636243** [comment]
白屏这个，我觉得还是得认真解决下，我发现每次白屏的时候，都会报那个空指针，然后报了很多的ContactsFragment初始化数据错误，但是我个人感觉这块应该联系不到这里

**Comment by quhong** [comment]
[https://github.com/GitLqr/LQRWeChat/blob/1f952f1fe7315904e93a1a587dca6d0bd0e1f841/app/src/main/java/com/lqr/wechat/utils/PinyinUtils.java#L39](url)

因为PinyinUtils.getPinyin这个方法判断传入的值漏掉了特殊字符
需要加上
 if (c >= -127 && c < 128 || !(c >= 0x4E00 && c <= 0x9FA5)) {
      sb.append(c);
  }

**Comment by zzq5636243** [comment]
if (c >= -127 && c < 128 || !(c >= 0x4E00 && c <= 0x9FA5)) {
                // 肯定不是汉字
                sb.append(c);
            } else {
                String s = "";
                try {
                    // 通过char得到拼音集合. 单 -> dan, shan
                    // 此处会报空指针错误
                    s = PinyinHelper.toHanyuPinyinStringArray(c, format)[0];
                    sb.append(s);
                } catch (BadHanyuPinyinOutputFormatCombination e) {
                    e.printStackTrace();
                    sb.append(s);
                }
            }
是这样吗？就是在拼接c的时候，加上判断？

**Comment by quhong** [comment]
是的
