### ISSUE TITLE
第一个问题，空指针

### ISSUE THREAD

**Issue by zzq5636243** [GitLqr/LQRWeChat#12]
java.lang.NullPointerException
02-20 10:32:39.327 13503-13503/com.lqr.wechat W/System.err:     at com.lqr.wechat.utils.PinyinUtils.getPinyin(PinyinUtils.java:46)
02-20 10:32:39.327 13503-13503/com.lqr.wechat W/System.err:     at com.lqr.wechat.model.Contact.fit(Contact.java:53)
02-20 10:32:39.327 13503-13503/com.lqr.wechat W/System.err:     at com.lqr.wechat.model.Contact.<init>(Contact.java:32)
02-20 10:32:39.327 13503-13503/com.lqr.wechat W/System.err:     at com.lqr.wechat.fragment.ContactsFragment.setDataAndUpdateView(ContactsFragment.java:235)
02-20 10:32:39.327 13503-13503/com.lqr.wechat W/System.err:     at com.lqr.wechat.fragment.ContactsFragment.initData(ContactsFragment.java:124)

**Comment by GitLqr** [comment]
我项目运行是没有问题的，这种常见异常就要靠你自己解决了哈

**Comment by zzq5636243** [comment]
这个空指针，我也还没注意看，但是整体来说，联系人列表那是肯定有问题了。不过我暂时也不太知道为什么切换的时候会出问题了

**Comment by zzq5636243** [comment]
这个空指针，还是出在了汉语转拼音的那个方法里，主要是sdk方法内部报了空指针

**Comment by zzq5636243** [comment]
如果可以，还是希望作者更换了这个对应的sdk吧
