### ISSUE TITLE
登入問題

### ISSUE THREAD

**Issue by tonyyang924** [GitLqr/LQRWeChat#14]
請問此專案有後端伺服器處理帳號登入嗎
使用列表上的帳號無法成功登入

**Comment by 1136066873** [comment]
按照提供的账号登录不了

**Comment by herryzhang** [comment]
没有你的邮件，听说你最近在找工作，所以我只能在这边联系你，我的QQ 858570636

**Comment by GitLqr** [comment]
刚刚试了，可以啊。。。

**Comment by herryzhang** [comment]
希望你可以联系我，858570636@qq.com

**Comment by tonyyang924** [comment]
請問跟地點有關係嗎？我在台灣會不會有影響

**Comment by tonyyang924** [comment]
哈 沒事
發現用qiwa帳號就能登入了
