### ISSUE TITLE
白屏不能的原因是出现栈溢出了

### ISSUE THREAD

**Issue by leonsimple** [GitLqr/LQRWeChat#18]
在ContactsFragment 的initData 方法出现异常时会不断递归调用initData，最终异常退出。异常的原因是有个空指针异常。
java.lang.NullPointerException
W:     at com.lqr.wechat.utils.PinyinUtils.getPinyin(PinyinUtils.java:46)
W:     at com.lqr.wechat.model.Contact.fit(Contact.java:53)
W:     at com.lqr.wechat.model.Contact.<init>(Contact.java:32)
W:     at com.lqr.wechat.fragment.ContactsFragment.setDataAndUpdateView(ContactsFragment.java:234)
W:     at com.lqr.wechat.fragment.ContactsFragment.initData(ContactsFragment.java:124)
W:     at com.lqr.wechat.activity.MainActivity$1.onPageSelected(MainActivity.java:272)
W:     at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1961)
W:     at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:689)
W:     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
W:     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
W:     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
W:     at com.lqr.wechat.activity.MainActivity.click(MainActivity.java:146)
W:     at com.lqr.wechat.activity.MainActivity$$ViewInjector$2.doClick(MainActivity$$ViewInjector.java:72)
W:     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)

**Comment by GitLqr** [comment]
如果你能解决的话，可以提交给我，我来合并，谢谢哈

**Comment by leonsimple** [comment]
可以，不过最近忙等段时间在上传，主要的原因是dawa的帐号有问题，联系人备注名为：“。。。”，这样的字符导致PinyinUtils报空指针，从而无限递归调用initData，方法栈溢出白屏。解决的方法：对PinyinUtils抓空处理，同时对initData方法调用发生异常后不要无限递归调用。

**Comment by GitLqr** [comment]
对，之前有网友说了拼音没有考虑到特殊字符，也给出了特殊字符处理的方法，不过我忘了他的代码放哪了，我明天去公司找找看。

**Comment by GitLqr** [comment]
找到了，在Issues11里，你可以试试

**Comment by leonsimple** [comment]
看到了
