### ISSUE TITLE
EmotionKeyboard这样用更简单，

### ISSUE THREAD

**Issue by leonsimple** [GitLqr/LQRWeChat#19]
/**
     * 初始化软件键盘控制
     */
    private void initEmotionKeyboard() {
        mEmotionKeyboard = EmotionKeyboard.with(this);
        mEmotionKeyboard.bindToEditText(editMessage);
        mEmotionKeyboard.bindToContent(contentView);
        mEmotionKeyboard.setEmotionView(viewBottom);
        mEmotionKeyboard.bindToEmotionButton(btnEmoji, btnMore);
        mEmotionKeyboard.setOnEmotionButtonOnClickListener(new EmotionKeyboard.OnEmotionButtonOnClickListener() {
            @Override
            public boolean onEmotionButtonOnClickListener(View view) {
                switch (view.getId()) {
                    case R.id.btn_more:
                        if (!viewMore.isShown()) {
                            if (viewEmoji.isShown()) {
                                viewMore.setVisibility(View.VISIBLE);
                                viewEmoji.setVisibility(View.GONE);
                                return true;
                            }
                            viewMore.setVisibility(View.VISIBLE);
                            viewEmoji.setVisibility(View.GONE);
                        }
                        break;
                    case R.id.btn_emoji:
                        if ( !viewEmoji.isShown()){
                            if (viewMore.isShown()) {
                                viewMore.setVisibility(View.GONE);
                                viewEmoji.setVisibility(View.VISIBLE);
                                return true;
                            }
                            viewMore.setVisibility(View.GONE);
                            viewEmoji.setVisibility(View.VISIBLE);
                        }
                        break;
                }
                return false;
            }
        });

    }
在加上这个触摸消息内容关闭效果更佳
contentView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                switch (event.getAction()) {
                    case MotionEvent.ACTION_DOWN:
                        closeBottomAndKeyboard();
                        break;
                }
                return false;
            }
        });

  private void closeBottomAndKeyboard() {
        viewBottom.setVisibility(View.GONE);
        viewEmoji.setVisibility(View.GONE);
        viewMore.setVisibility(View.GONE);
        if (mEmotionKeyboard != null) {
            mEmotionKeyboard.hideSoftInput();
        }
    }

**Comment by GitLqr** [comment]
good,thanks you very much!
