### ISSUE TITLE
输入法和表情界面切换时闪屏

### ISSUE THREAD

**Issue by wcglws** [GitLqr/LQRWeChat#20]
大神：输入法和表情界面切换时，表情界面会瞬间置顶闪屏这个是怎么回事啊？

**Comment by GitLqr** [comment]
之前没控制好，你可以看看我这个http://www.jianshu.com/p/a90998628112，里面有完美Demo

**Comment by wcglws** [comment]
还有个现象，进入聊天界面先把表情界面显示出来，然后按home键让APP进入后台，然后在回到APP，输入法会把整个表情界面顶上去

**Comment by GitLqr** [comment]
那是因为Edittext自己获取了焦点导致的，不是我lib库的问题，你可以在自己项目中对Edittext进行控制
