### ISSUE TITLE
导入出错

### ISSUE THREAD

**Issue by hfkai** [GitLqr/LQRWeChat#4]
定义重复 
![b t2hh6e2n 4n7n9hirx4e](https://cloud.githubusercontent.com/assets/12794733/22776062/3ac4c7aa-eee9-11e6-9fb8-b8ab8d8a8685.png)

**Comment by GitLqr** [comment]
怎么会有values-v24这个文件夹？看源码中是不是有多出的values文件夹，有的话删除，重新编译。因为没有做适配和国际化，所以本项目只有一个values而已。

**Comment by ahangchen** [comment]
@GitLqr 在readme里说明一下你的gradle和Android sdk版本比较好，这个应该是版本的问题，新版本sdk里有title这个属性

**Comment by ahangchen** [comment]
@hfkai 你用的sdk版本应该跟作者的不一样
