### ISSUE TITLE
jackson和fastjson出现内容重复，无法启动

### ISSUE THREAD

**Issue by zzq5636243** [GitLqr/LQRWeChat#8]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/services/javax.ws.rs.ext.MessageBodyReader
	File1: C:\Users\nene\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.jaxrs\jackson-jaxrs-json-provider\2.7.3\1752f25fc88409d5b2e57820a8c4bb165022ecd7\jackson-jaxrs-json-provider-2.7.3.jar
	File2: C:\Users\nene\.gradle\caches\modules-2\files-2.1\com.alibaba\fastjson\1.2.23\be2508e9bac203c38f3f52fc8d33332c4e7ee6c5\fastjson-1.2.23.jar

我在运行这个项目的时候，出现了上述问题，我看了下你的代码，是两个包都需要用到，那么如何解决相应的重复呢？

**Comment by GitLqr** [comment]
建议去掉其中的一种，开发中尽量不要使用重复同种功能的第三方库，会使得apk体积变大，还会造成不必要的编码障碍。

**Comment by zzq5636243** [comment]
但是你的demo里就带有这个，然后我准备去了的时候，错误太多，就没去了，所以就先问你

**Comment by GitLqr** [comment]
嗯？应该也好改吧？这样，你找到项目代码中使用到JacksonUtils.java的代码部分，全部修改为你自己的工具类代码（fastjson），然后把JacksonUtils.java删掉；最后记得去掉build.gradle中jackson的jcenter引用。我旧的这样做应该没什么问题了。
